packages:
  - 'packages/*'
  - '!playgrounds'

catalogs:
  build:
    '@vitejs/plugin-vue': 6.0.1
    tsc-alias: 1.8.16
    vite: 7.1.2
    vue-tsc: 3.0.5

  dev:
    '@antfu/eslint-config': ^5.2.1
    eslint: 9.33.0
    eslint-plugin-format: ^1.0.1

  framework:
    element-plus: ^2.8.10
    vee-validate: 4.15.1
    vue: '>=3.5'

  test:
    vitest: ^3.2.4

  tooling:
    '@changesets/cli': 2.29.5

  types:
    '@types/node': 24.2.1
    typescript: 5.9.2
