packages:
  - 'packages/*'
  - '!playgrounds'

catalogs:
  build:
    '@vitejs/plugin-vue': 6.0.1
    tsc-alias: 1.8.16
    vite: 7.1.2
    vue-tsc: 3.0.5

  dev:
    '@antfu/eslint-config': 5.2.1
    eslint: 9.33.0
    eslint-plugin-format: 1.0.1

  framework:
    '@bach.software/vue-dynamic-form': '>=0.1.0'
    element-plus: '>=2.0.0'
    vee-validate: '>=4.15'
    vue: '>=3.5'

  test:
    '@vue/test-utils': 2.4.6
    jsdom: 26.0.0
    vitest: 3.2.4

  tooling:
    '@changesets/cli': 2.29.5

  types:
    '@types/node': 24.2.1
    typescript: 5.9.2
