sonar.projectKey=vue-dynamic-form
sonar.projectName=Vue Dynamic Form

sonar.sources=packages/core/src,packages/element-plus/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.d.ts,**/coverage/**,src/tests/**,src/examples/**

sonar.tests=packages/core/src,packages/element-plus/src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts

sonar.javascript.lcov.reportPaths=packages/core/coverage/lcov.info,packages/element-plus/coverage/lcov.info

sonar.sourceEncoding=UTF-8
